version: 2

models:
  # ------------------ DIMENSIONS ------------------
  - name: dim_product
    description: "Products dimension table"
    columns:
      - name: product_pk
        description: "Primary key for product"
        tests:
          - unique
          - not_null
      - name: stock_code
        description: "Original stock code from source"
        tests:
          - not_null
      - name: product_description
        description: "Product description"
        tests:
          - not_null

  - name: dim_customer
    description: "Customers dimension table"
    columns:
      - name: customer_pk
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Original customer ID from source"
        tests:
          - not_null
      - name: customer_country
        description: "Country of the customer"
        tests:
          - not_null

  - name: dim_date
    description: "Date dimension table"
    columns:
      - name: date_pk
        description: "Primary key for date"
        tests:
          - unique
          - not_null
      - name: invoice_date
        description: "Original invoice date"
        tests:
          - not_null
      - name: year
        description: "Year of invoice"
        tests:
          - not_null
      - name: month
        description: "Month of invoice"
        tests:
          - not_null
      - name: day
        description: "Day of invoice"
        tests:
          - not_null

  # ------------------ FACTS ------------------
  - name: fct_sales
    description: "Sales fact table"
    columns:
      - name: invoice_no
        tests:
          - not_null
      - name: product_fk
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_pk
      - name: customer_fk
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_pk
      - name: date_fk
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_pk
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: total_price
        tests:
          - not_null

  - name: fct_daily_sales
    description: "Aggregated daily sales fact table"
    columns:
      - name: date_fk
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_pk
      - name: total_quantity
        tests:
          - not_null
      - name: total_sales
        tests:
          - not_null

  - name: fct_customer_activity
    description: "Customer activity fact table"
    columns:
      - name: customer_fk
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_pk
      - name: total_orders
        tests:
          - not_null
      - name: total_spent
        tests:
          - not_null
